# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1voo5eB1z2XmFweWaX1gwTXx89MXCAF2g
"""

import pandas as pd
import matplotlib.pyplot as plt
a=pd.read_csv("/content/temp.csv")
print(a)
mv=a["Temperature"].mean()
max=a["Temperature"].max()
min=a["Temperature"].min()
a=a.fillna(mv)
print(mv)
print(max)
print(min)
day=0
for i in a['Temperature']:
  if(i>mv):
    day=day+1
print("\nNumber of days where the temperature exceeded the threshold is",day,"\n")
plt.plot(a['Day'],a["Temperature"],color='black')
plt.title("Temperature")
plt.show()